version: "3.7"
services:

  proxy:
    image: icgood/proxy-service
    deploy:
      mode: global
    entrypoint: >-
      proxyprotocol-server
        --service :143 pymap:143
        --service :4190 pymap:4190
        --service :25 slimta-edge:25
        --service :587 slimta-edge:587
    ports:
      - target: 143
        published: 143
        protocol: tcp
        mode: host
      - target: 4190
        published: 4190
        protocol: tcp
        mode: host
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data

  pymap:
    image: slimta/pymap
    build:
      context: ./pymap
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private
    ports:
      - "9090:9090"

  slimta-edge:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-relay
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - spamd
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  slimta-relay:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-edge
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - pymap
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  letsencrypt:
    image: icgood/letsencrypt-service
    environment:
      CERTS: mail
      DOMAIN_mail: ${FQDN}
      ALTS_mail: ${ALTS}
    secrets:
      - lexicon_env
    deploy:
      mode: global
      restart_policy:
        delay: 10m
    volumes:
      - dehydrated-data:/var/lib/dehydrated
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  spamd:
    image: slimta/spamassassin
    build:
      context: ./spamassassin

secrets:
  lexicon_env:
    file: $HOME/.docker-secrets/lexicon.env

volumes:
  redis-data:
  dehydrated-data:
