version: "3.7"
services:

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data

  pymap:
    image: slimta/pymap
    build:
      context: ./pymap
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private
    ports:
      - "143:143"
      - "4190:4190"
      - "9090:9090"

  slimta-edge:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-relay
    deploy:
      mode: global
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - spamd
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host

  slimta-relay:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-edge
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - pymap
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  letsencrypt:
    image: slimta/letsencrypt
    build:
      context: ./letsencrypt
    environment:
      DOMAINS: mail
      DOMAIN_LN_mail: ${FQDN}
    secrets:
      - lexicon_env
    deploy:
      mode: global
      restart_policy:
        delay: 10m
    volumes:
      - dehydrated-data:/var/lib/dehydrated
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  spamd:
    image: slimta/spamassassin
    build:
      context: ./spamassassin

secrets:
  lexicon_env:
    file: $HOME/.docker-secrets/lexicon.env

volumes:
  redis-data:
  dehydrated-data:
