version: "3.7"
services:

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  pymap:
    image: pymap
    build:
      context: ./pymap
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - "143:143"

  slimta-edge:
    image: slimta-edge
    build:
      context: ./slimta
      args:
        slimta_config: edge.yaml
    environment:
      REDIS_HOST: redis
      SPAMD_HOST: spamassassin
    env_file: /opt/slimta-docker/etc/host.env
    depends_on:
      - redis
      - spamassassin
    volumes:
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - "1025:1025"
      - "587:587"
      - "25:25"
      - "1587:1587"

  slimta-relay:
    image: slimta-relay
    build:
      context: ./slimta
      args:
        slimta_config: relay.yaml
        extra_install: pymap-admin
    environment:
      REDIS_HOST: redis
      PYMAP_HOST: pymap
    env_file: /opt/slimta-docker/etc/host.env
    depends_on:
      - redis
      - pymap
    volumes:
      - /etc/ssl/private:/etc/ssl/private

  spamassassin:
    build:
      context: ./spamassassin

volumes:
  redis-data:
