version: "3.8"
services:

  proxy:
    image: icgood/proxy-protocol
    deploy:
      mode: global
    command: >-
      --dnsbl xbl.spamhaus.org
      --service :143 pymap:143
      --service :4190 pymap:4190
      --service :50051 pymap:50051?pp=noop
      --service :25 slimta-edge:25
      --service :587 slimta-edge:587
    ports:
      - target: 143
        published: 143
        protocol: tcp
        mode: host
      - target: 4190
        published: 4190
        protocol: tcp
        mode: host
      - target: 50051
        published: 50051
        protocol: tcp
        mode: host
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data

  pymap:
    image: icgood/pymap
    depends_on:
      - redis
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private
    environment:
      FQDN: ${FQDN}
      SWIM_SECRET_FILE: /run/secrets/pymap_swim_secret
      SWIM_NAME: tasks.pymap:9999
      CERT_FILE: /etc/ssl/private/mail/fullchain.pem
      KEY_FILE: /etc/ssl/private/mail/privkey.pem
    secrets:
      - pymap_swim_secret
    command: >-
      --debug
      --proxy-protocol detect
      --swim-udp-discovery
      redis
      --address redis://redis
      --prefix pymap
      --users-prefix slimta/address
      --data-address redis://redis/1
    deploy:
      replicas: 2
    networks:
      default:
        aliases:
          - ${PYMAP_HOST}

  slimta-edge:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-relay
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - spamd
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private
    networks:
      default:
        aliases:
          - ${SLIMTA_HOST}

  slimta-relay:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-edge
    environment:
      FQDN: ${FQDN}
      PYMAP_ADMIN_HOST: ${PYMAP_HOST}
      PYMAP_ADMIN_PORT: 50051
    secrets:
      - pymap_admin_token
    depends_on:
      - redis
      - pymap
    volumes:
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  letsencrypt:
    image: icgood/letsencrypt-service
    environment:
      CERTS: mail
      DOMAIN_mail: ${FQDN}
      ALTS_mail: "${PYMAP_HOST} ${SLIMTA_HOST} ${MX_HOSTS} ${ALTS}"
    secrets:
      - lexicon_env
    deploy:
      mode: global
      restart_policy:
        delay: 10m
    volumes:
      - dehydrated-data:/var/lib/dehydrated
      - ${CERT_DIR:-/etc/ssl/private}:/etc/ssl/private

  spamd:
    image: slimta/spamassassin
    build:
      context: ./spamassassin

secrets:
  lexicon_env:
    file: $HOME/.docker-secrets/lexicon.env
  pymap_admin_token:
    file: $HOME/.docker-secrets/pymap-admin.token
  pymap_swim_secret:
    file: $HOME/.docker-secrets/pymap-swim-secret

volumes:
  redis-data:
  dehydrated-data:
