version: "3.7"
services:

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  pymap:
    image: slimta/pymap
    build:
      context: ./pymap
    depends_on:
      - redis
    volumes:
      - private-data:/etc/ssl/private
    ports:
      - "143:143"

  slimta-edge:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-relay
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - spamd
    volumes:
      - private-data:/etc/ssl/private
    ports:
      - "25:25"
      - "587:587"

  slimta-relay:
    image: slimta/slimta
    build:
      context: ./slimta
    entrypoint: slimta --no-edge
    environment:
      FQDN: ${FQDN}
    depends_on:
      - redis
      - pymap
    volumes:
      - private-data:/etc/ssl/private

  letsencrypt:
    image: slimta/letsencrypt
    build:
      context: ./letsencrypt
    environment:
      FQDN: ${FQDN}
    secrets:
      - lexicon_env
    volumes:
      - letsencrypt-data:/var/lib/dehydrated
      - private-data:/etc/ssl/private

  spamd:
    image: slimta/spamassassin
    build:
      context: ./spamassassin

secrets:
  lexicon_env:
    file: ./lexicon.env

volumes:
  redis-data:
  letsencrypt-data:
  private-data:
