version: "3.7"
services:

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  pymap:
    image: slimta/pymap
    build:
      context: ./pymap
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - private-data:/etc/ssl/private
    ports:
      - "143:143"

  slimta-edge:
    image: slimta/slimta-edge
    build:
      context: ./slimta
      args:
        slimta_config: edge.yaml
    environment:
      FQDN: ${FQDN}
      REDIS_HOST: redis
      SPAMD_HOST: spamassassin
    depends_on:
      - redis
      - spamassassin
    volumes:
      - private-data:/etc/ssl/private
    ports:
      - "25:25"
      - "587:587"

  slimta-relay:
    image: slimta/slimta-relay
    build:
      context: ./slimta
      args:
        slimta_config: relay.yaml
        extra_install: pymap-admin
    environment:
      FQDN: ${FQDN}
      REDIS_HOST: redis
      PYMAP_HOST: pymap
    depends_on:
      - redis
      - pymap
    volumes:
      - private-data:/etc/ssl/private

  letsencrypt:
    image: slimta/letsencrypt
    build:
      context: ./letsencrypt
    environment:
      FQDN: ${FQDN}
    env_file: lexicon.env
    volumes:
      - letsencrypt-data:/var/lib/dehydrated
      - private-data:/etc/ssl/private

  spamassassin:
    image: slimta/spamassassin
    build:
      context: ./spamassassin

volumes:
  redis-data:
  letsencrypt-data:
  private-data:
